[<%= checkEvent.message.toUpperCase() %>]Â Check "<%= check.name %>" just went <%= checkEvent.message %>
On <%= moment(checkEvent.timestamp).format('LLLL') %>,
<% if (checkEvent.message == 'down') { -%>
    a test on URL "<%= check.url %>" failed with the following error:

        <%= checkEvent.details %>
<% } else if (checkEvent.message == 'up') { -%>
    <% if (checkEvent.downtime) { -%>
        and after <%= moment.duration(checkEvent.downtime).humanize() %> of downtime,
    <% }%>
    a test on URL "<%= check.url %>" responded correctly.
<% } else { -%>
    check "<%= check.url %>" was manually <%= checkEvent.message %>.
<% } -%>

For details, check <%= url %>/dashboard/checks/<%= check._id %>?type=hour&date=<%= checkEvent.timestamp.valueOf() %>

Uptime won't send anymore emails about this check until it goes back up.
---------------------------------------------------------------------
This is an automated email sent from Uptime. Please don't reply to it.
